### ISSUE TITLE
Rectrict to admins only

### ISSUE THREAD

**Issue by creecros** [kenlog/UpdateNotifier#1]
Suggest to not notify normal users.

**Comment by kenlog** [comment]
Yes, even in the company they told me the same. One thing certainly to add. I'll do it shortly. 
What do you think about this plugin? For me it was very stressful to always check for new updates, then I created this plugin that resolved, by pointing out the new versions of the plugins.

**Comment by creecros** [comment]
Very useful!

**Comment by creecros** [comment]
Fixed with #2
