### ISSUE TITLE
App shows that already installed new Kanboard version is available

### ISSUE THREAD

**Issue by ntimo** [kenlog/UpdateNotifier#10]
Hello,
when I open the main page of my Kanboard docker installation, I am greeted with a huge big green bar at the top saying "New version: Kanboard v1.2.9". But this is simply wrong since I am already running 1.2.9. Is this some kind of a bug?

In the settings under Configuration Kanboard says "Application version: 1.2.9"

**Comment by creecros** [comment]
Since your using docker, just to be sure, restart every container including any databases associated. 

Confirm latest version of plug in as well. 
Should be 1.4.0.

**Comment by creecros** [comment]
Don't bother I was able to duplicate. I'll take a look tonight.

**Comment by creecros** [comment]
hmmm...

```phph
error_log(trim(preg_replace('/[A-Za-z]/', '', $value->title), ' '), 0);                        error_log($applications_version, 0);
```

both return:

```
PHP message: 1.2.9
PHP message: 1.2.9
```

What the hell am i missing?
https://www.php.net/manual/en/function.version-compare.php

**Comment by creecros** [comment]
It was whitespace.
https://github.com/kenlog/UpdateNotifier/releases/tag/1.4.1
