### ISSUE TITLE
App shows that already installed new Kanboard version is available

### ISSUE THREAD

**Issue by Ryonez** [kenlog/UpdateNotifier#12]
Basically same as the last one, using the official docker image on the latest version (v1.2.10).

**Comment by creecros** [comment]
@kenlog Its the added "v" in the version. Need to strip it out.  If you get to it before me, just see https://github.com/creecros/Customizer/commit/30c2e1bf1e00ceb812f3e36410c98c2ad25e3160

**Comment by Ryonez** [comment]
@creecros cleaned it up in his theme. Thank you.

**Comment by creecros** [comment]
https://github.com/kenlog/UpdateNotifier/releases/tag/v1.4.3

should take care of it. key word is "should", didn't actually test it. let us know otherwise.
