### ISSUE TITLE
Latest Plugins Page Displays an Error

### ISSUE THREAD

**Issue by Ryonez** [kenlog/UpdateNotifier#13]
When clicking the link added by this extension called 'Latest Plugins" I get the following back:
```
Internal Error: SQL Error: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "plugin_dates" does not exist LINE 1: INSERT INTO "plugin_dates" ("name", "date_creation") VALUES ... ^
```

I don't know if this plugin uses it's own database file, but Kanban's database is postgres for me.

**Comment by creecros** [comment]
Postgres. Sadface. I'll have to retest. Dont generally have a postgres container laying around.

**Comment by creecros** [comment]
oh...duh.

**Comment by Ryonez** [comment]
The plugin version still shows 1.4.2, and the error is still the same when using the release download.

**Comment by creecros** [comment]
I just double checked install file, and tested. Everything works. 

Please confirm you are using the latest install file: https://github.com/kenlog/UpdateNotifier/releases/download/v1.4.3/UpdateNotifier-1.4.3.zip

Make sure you restart your server in order for the DB migration to take effect.

Working test site with latest plugin installed, running KB 1.2.10 and Postgres:
https://projects.nachostudio.ml

user: admin
pw: admin

**Comment by Ryonez** [comment]
Alright, restarting the docker is what did the trick. Not sure how it loaded the old deleted files, but hey.

Thank you for your time and help Creecros.

**Comment by creecros** [comment]
The docker container is set to cache php files. You have to restart for changes to code, or update the php.ini to not cache php files.

**Comment by Ryonez** [comment]
Interesting. I would have though seeing as it removes plugins when deleted, and adds them when it detects it, that is was more dynamic. I'll have to keep that in mind for the future.

**Comment by creecros** [comment]
If you wanted to change that, go to 
`etc/php7/conf.d/local.ini`

Set the below to "on"
`opcache.validate_timestamps = On`

And add this line
`opcache.revalidate_freq = 0`

Restart container. Now, all changes to php code will be immediate and not require restarts.
