### ISSUE TITLE
PHP Notice: Undefined index

### ISSUE THREAD

**Issue by kenlog** [kenlog/UpdateNotifier#3]
@creecros I noticed this notification in the log. Some idea? I tried with "isset" but it's not good

**Comment by creecros** [comment]
when and where is it occurring? I'm not seeing it.

**Comment by creecros** [comment]
not showing up in my logs for v1.25 or 1.26, sure it's related to this plugin? copy the full log line.

**Comment by creecros** [comment]
didn't realize you had newer commits, i found it.

**Comment by creecros** [comment]
you had the right idea. isset is boolean though, so first determine if both are set, using && and then compare. so you needed both lines:
https://github.com/kenlog/UpdateNotifier/blob/a98da91ee29ce2814839699caa22d94af62385ec/Helper/Notifier.php#L35-L36

**Comment by kenlog** [comment]
Hi @creecros, here's a good thing this morning! Excellent solution :1st_place_medal:
