### ISSUE TITLE
Notify the new plugins

### ISSUE THREAD

**Issue by kenlog** [kenlog/UpdateNotifier#8]
Hi @creecros I thought it would be nice to also notify the new plugins, in a non-invasive way, for example by displaying a colored dot or a specific icon in the header. What do you say?

**Comment by creecros** [comment]
Newly released plugins that didn’t once exist? Sounds cool to me. Maybe include the word “New” on the directory page for new plugins?

**Comment by kenlog** [comment]
yes @creecros , add the "new" or "last added" plugins in the sidebar of the page, which returns for example the last 10 plugins. Let's find a way to calculate the publication time so that you always return the last 10 published. With the timestamp it would be ideal. Do you imagine an alternative way?

**Comment by creecros** [comment]
Alternative:
- Save a list of all plugins to metadata.
- Compare to list from json. 
- When lists don't match, Put a "New" tag on the plugins that aren't in the list saved in metadata
- Update the saved list in metadata

**Comment by kenlog** [comment]
> Alternative:
> 
> * Save a list of all plugins to metadata.
> * Compare to list from json.
> * When lists don't match, Put a "New" tag on the plugins that aren't in the list saved in metadata
> * Update the saved list in metadata

Hi @creecros I wrote this code in raw PHP as a starting point for reasoning together https://gist.github.com/kenlog/3038223fc631b1575068b43ca666f1cc

**Comment by kenlog** [comment]
Hi @creecros I have little time this week because I have work to deliver. In any case if you can start a new branch. Maybe Sunday or Monday I can give my contribution.

**Comment by creecros** [comment]
@kenlog 

Added Schema and a Model, use the model to:
- `getAll()` plugins
- `getTen()` plugins
- `save($name)` for each plugin
- `exists($name)` to check if exists

How to use: Need to add a controller that will take the json, and save each plugin name to the database. It will check if the name exists, and if not it will add a record and timestamp. For the Show in the controller, simply use getTen(), to get the ten latest plugins, and then use that to filter back out of the json to only show those ten.

Added empty templates. Need to add a controller. Ran out of time, I'll try and pick back up later today.

**Comment by creecros** [comment]
Nevermind, I completed.

Keep in mind, the first time it's run, the 10 latest plugins will simply be the last ten plugins insterted into the Database. Once new plugins are added from here on out, they will appear.

**Comment by creecros** [comment]
Although, that might be confusing, so what I could do is, make it so nothing shows until new plugins are added.

**Comment by creecros** [comment]
Implemented the above. The first time this plugin runs, with the update, it will add all the plugins available from json to the database with `0` as the time stamp, and then it adds a setting in configModel with a value of `1`. The next time the controller runs, it will see that setting and start to add plugins that don't exist in the DB with a timestamp. When the model grabs the latest 10, it will exclude timestamps with `0`, thus the first time this plugin is updated or installed, there will be nothing in the latest plugin page, until new plugins are added to kanboard's json feed.

**Comment by kenlog** [comment]
@creecros Wahoo! I like it, you did a great job! :+1:

**Comment by creecros** [comment]
@kenlog Thanks! Feel free to change what you want to better suit your vision, but I think it does what you were wanting.

**Comment by kenlog** [comment]
Fantastic! If you agree, you can merge to the master branch. :1st_place_medal:

**Comment by kenlog** [comment]
@creecros Many thanks!

**Comment by creecros** [comment]
@kenlog 
Anytime!

just saw a typo, fixed, and remade the release.

**Comment by kenlog** [comment]
Yes, I noticed, no problem.
